name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name "mr1326"
        git config --global user.email ""
        git config pull.rebase false
        git pull
        rm -f skymine.zip
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'skymine.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: push changes to remote
      run: |
        git add -A
        git commit -m "new pack"
        git push --force
