name: Resource Pack
on:
  push:
    tags:
      - 'v*'  # Trigger the workflow on tags that start with "v"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checkout the code from the repository
    - name: Checkout code from main repo
      uses: actions/checkout@v2

    # Extract the version number from your resource pack file (or another file where it's stored)
    - name: Extract version from resource pack description
      id: version
      run: |
        # Read the description from the resource pack file (or a specific file where version is stored)
        description=$(cat pack.mcmeta)
        
        # Use regex to extract the version number (e.g., 'V 6.0.1')
        version=$(echo "$description" | grep -oP 'V \d+\.\d+\.\d+' | awk '{print $2}')
        
        # Set the extracted version to an environment variable for later steps
        echo "VERSION=$version" >> $GITHUB_ENV
        echo "Extracted version: $version"

    # Archive the release (we won't push the .zip file to the repository)
    - name: Archive Resource Pack Release (no push to repo)
      uses: thedoctor0/zip-release@master
      with:
        filename: "SkyMineRP-${{ env.VERSION }}.zip"  # Append version to the filename
        exclusions: '*.git* /*node_modules/* .editorconfig'  # Exclude unnecessary files

    # Create GitHub Release and Upload ZIP File (no need to store in main repo)
    - name: Create GitHub Release and Upload ZIP File
      uses: softprops/action-gh-release@v1
      with:
        files: SkyMineRP-${{ env.VERSION }}.zip  # Attach the .zip file to the release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This is automatically available for GitHub Actions workflows
