name: Resource Pack
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checkout the code from the repository
    - name: Checkout code from main repo
      uses: actions/checkout@v2

    # Extract the version number from your resource pack file
    - name: Extract version from resource pack description
      id: version
      run: |
        description=$(cat pack.mcmeta)
        version=$(echo "$description" | grep -oP 'V \d+\.\d+\.\d+' | awk '{print $2}')
        echo "VERSION=$version" >> $GITHUB_ENV
        echo "Extracted version: $version"

    # Create a Git tag for the release
    - name: Create Git Tag
      run: |
        git tag -a "v${{ env.VERSION }}" -m "Release version ${{ env.VERSION }}"
        git push origin "v${{ env.VERSION }}"  # Push the tag to the repository

    # Archive the resource pack into a .zip file (without pushing to the repo)
    - name: Archive Resource Pack
      uses: thedoctor0/zip-release@master
      with:
        filename: "SkyMineRP-${{ env.VERSION }}.zip"  # Append version to the filename
        exclusions: '*.git* /*node_modules/* .editorconfig'  # Exclude unnecessary files

    # Create GitHub Release and upload the .zip file as an asset
    - name: Create GitHub Release and Upload ZIP File
      uses: softprops/action-gh-release@v1
      with:
        files: resourcepack-${{ env.VERSION }}.zip  # Attach the .zip file to the release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically available GitHub Actions token
